# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cuda_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 450)
        self.confirmBox = QtWidgets.QDialogButtonBox(Dialog)
        self.confirmBox.setGeometry(QtCore.QRect(10, 340, 761, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.confirmBox.setFont(font)
        self.confirmBox.setOrientation(QtCore.Qt.Horizontal)
        self.confirmBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirmBox.setObjectName("confirmBox")
        self.logo_pic = QtWidgets.QLabel(Dialog)
        self.logo_pic.setGeometry(QtCore.QRect(352, 50, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.logo_pic.setFont(font)
        self.logo_pic.setText("")
        self.logo_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_pic.setObjectName("logo_pic")
        self.cuda_msg = QtWidgets.QLabel(Dialog)
        self.cuda_msg.setGeometry(QtCore.QRect(40, 160, 711, 141))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cuda_msg.setFont(font)
        self.cuda_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.cuda_msg.setObjectName("cuda_msg")

        self.retranslateUi(Dialog)
        self.confirmBox.accepted.connect(Dialog.accept) # type: ignore
        self.confirmBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cuda_msg.setText(_translate("Dialog", "Error: Please check CUDA environment"))
