# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/passwd_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 450)
        self.confirmBox = QtWidgets.QDialogButtonBox(Dialog)
        self.confirmBox.setGeometry(QtCore.QRect(40, 350, 731, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.confirmBox.setFont(font)
        self.confirmBox.setOrientation(QtCore.Qt.Horizontal)
        self.confirmBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.confirmBox.setObjectName("confirmBox")
        self.tips = QtWidgets.QLabel(Dialog)
        self.tips.setGeometry(QtCore.QRect(32, 186, 731, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tips.setFont(font)
        self.tips.setObjectName("tips")
        self.logoPic = QtWidgets.QLabel(Dialog)
        self.logoPic.setGeometry(QtCore.QRect(352, 48, 100, 70))
        self.logoPic.setText("")
        self.logoPic.setAlignment(QtCore.Qt.AlignCenter)
        self.logoPic.setObjectName("logoPic")
        self.infoLabel = QtWidgets.QLabel(Dialog)
        self.infoLabel.setGeometry(QtCore.QRect(170, 300, 591, 31))
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(170, 251, 280, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.password.setFont(font)
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pw = QtWidgets.QLabel(Dialog)
        self.pw.setGeometry(QtCore.QRect(32, 251, 114, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pw.sizePolicy().hasHeightForWidth())
        self.pw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pw.setFont(font)
        self.pw.setObjectName("pw")

        self.retranslateUi(Dialog)
        self.confirmBox.accepted.connect(Dialog.accept)  # type: ignore
        self.confirmBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tips.setText(_translate(
            "Dialog", "Administrator privileges are required, please enter your password"))
        self.pw.setText(_translate("Dialog", "password:"))
